function Y = ShaftElementStiffness(min,max,y,d_FAI,d_FAI_2,Wx,d_Wx,Wy,d_Wy,Wz,d_Wz,Feshi_u,Feshi_v,Feshi_w,Feshi_xita,Feshi_lamuda,Feshi_posai,ROUeshi,Seshi,Iseshimo,Eeshi,Geshi,keshimo)
%ShaftElementStiffness
%此函数返回轴有限元的单元刚度矩阵
%该矩阵由轴有限元的形状位置函数积分而成
%单元刚度矩阵Keshi(t)的大小为12 x 12。
a = Eeshi*Iseshimo*int(diff(Feshi_xita,y).'*diff(Feshi_xita,y)+diff(Feshi_posai,y).'*diff(Feshi_posai,y),min,max)...
    +Geshi*keshimo*Seshi*int((diff(Feshi_u,y)+Feshi_posai).'*((diff(Feshi_u,y)+Feshi_posai)),min,max)...
    +Geshi*keshimo*Seshi*int((diff(Feshi_w,y)-Feshi_xita).'*((diff(Feshi_w,y)-Feshi_xita)),min,max)...
    +Eeshi*Seshi*int(diff(Feshi_v,y).'*diff(Feshi_v,y),min,max)...
    +2*Geshi*Iseshimo*int(diff(Feshi_lamuda,y).'*diff(Feshi_lamuda,y),min,max);%Keshie
b = 2*ROUeshi*Iseshimo*int(Feshi_posai.'*Feshi_xita,min,max);%Keshig
c = ROUeshi*Seshi*int(Feshi_w.'*Feshi_v-Feshi_v.'*Feshi_w,min,max)...
    -2*ROUeshi*Iseshimo*int(Feshi_lamuda.'*Feshi_posai,min,max);%Keshi,su_diff(Wx)
d = ROUeshi*Seshi*int(Feshi_u.'*Feshi_w-Feshi_w.'*Feshi_u,min,max)...
    +ROUeshi*Iseshimo*int(Feshi_xita.'*Feshi_posai+Feshi_posai.'*Feshi_xita,min,max);%Keshi,su_diff(Wy)
e = ROUeshi*Seshi*int(Feshi_v.'*Feshi_u-Feshi_u.'*Feshi_v,min,max)...
    +2*ROUeshi*Iseshimo*int(Feshi_lamuda.'*Feshi_xita,min,max);%Keshi,su_diff(Wz)
f = 2*ROUeshi*Iseshimo*int(Feshi_xita.'*Feshi_xita+Feshi_posai.'*Feshi_posai,min,max);%Keshi,su_diff(FAI)_Wy
g = -ROUeshi*Seshi*int(Feshi_v.'*Feshi_v+Feshi_w.'*Feshi_w,min,max)...
    -ROUeshi*Iseshimo*int(Feshi_posai.'*Feshi_posai,min,max);%Keshi,su_Wx^2
h = -ROUeshi*Seshi*int(Feshi_u.'*Feshi_u+Feshi_w.'*Feshi_w,min,max)...
    +ROUeshi*Iseshimo*int(Feshi_xita.'*Feshi_xita+Feshi_posai.'*Feshi_posai,min,max);%Keshi,su_Wy^2
i = -ROUeshi*Seshi*int(Feshi_u.'*Feshi_u+Feshi_v.'*Feshi_v,min,max)...
    -ROUeshi*Iseshimo*int(Feshi_xita.'*Feshi_xita,min,max);%Keshi,su_Wz^2
j = ROUeshi*Seshi*int(Feshi_u.'*Feshi_v+Feshi_v.'*Feshi_u,min,max);%Keshi,su_WxWy
k = ROUeshi*Seshi*int(Feshi_u.'*Feshi_w+Feshi_w.'*Feshi_u,min,max)...
    +ROUeshi*Iseshimo*int(Feshi_xita.'*Feshi_posai+Feshi_posai.'*Feshi_xita,min,max);%Keshi,su_WxWz
l = ROUeshi*Seshi*int(Feshi_v.'*Feshi_w+Feshi_w.'*Feshi_v,min,max);%Keshi,su_WyWz
Y = a+b*d_FAI_2+c*d_Wx+d*d_Wy+e*d_Wz+f*d_FAI*Wy+g*Wx^2+h*Wy^2+i*Wz^2+j*Wx*Wy+k*Wx*Wz+l*Wy*Wz;%已检查
end